---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---


## 網站資料爬取
```{r}
#這是R Code Chunk
#install.packages("rvest")
library(rvest) ##第一次使用要先安裝 install.packages("rvest")

PTT <- read_html("https://www.ptt.cc/bbs/NBA/index.html")
btnURL <- PTT %>% html_nodes("a[class='btn wide']") %>% html_attr("href")
indexNum <- as.numeric(gsub("/bbs/NBA/index|.html","",btnURL[2]))

totalPage<-NULL
for (i in (indexNum-4):(indexNum+1)){
PTT = paste("https://www.ptt.cc/bbs/NBA/index",i,".html",sep="")
Title <- read_html(PTT) %>% html_nodes(".title") %>% html_text()
PushNum <- read_html(PTT) %>% html_nodes(".nrec") %>% html_text()
Author <- read_html(PTT) %>% html_nodes(".author") %>% html_text()
tempPage <- data.frame(Title, PushNum, Author)
totalPage <- rbind(totalPage, tempPage)
}
View(totalPage)



##read_html
##html_nodes
##html_text
```

## 爬蟲結果呈現
```{r}
#這是R Code Chunk
knitr::kable(totalPage) ##請將iris取代為上個步驟中產生的爬蟲資料資料框
```

## 解釋爬蟲結果 
```{r}
#這是R Code Chunk

dim(totalPage)
nrow(totalPage)
str(totalPage)

```


共爬出幾篇文章標題?
Ans: 2017/03/27抓到了122個標題('data.frame':	122 obs. of  3 variables)


```{r}
#這是R Code Chunk

table(totalPage$Author)
max(table(totalPage$Author))

```

哪個作者文章數最多？
Ans: 2017/03/27抓到的資料是Rambo有最多文章，有28篇。

有趣的現象
Ans: 以NBA看板為例，大約平均一天會有三頁資料，相當於每天有60筆資料。
我觀察到有趣的現象是大家好像比較少在別人的文章留言，都直接另外發一篇Re:XXXXX，可能大家喜歡自己當作者。
